"""Lightweight classes for defining and working with networks.

The Network class defined in this submodule is used to maintain the network
generated by NETGEN in memory.
"""

#=============================================================================

class Network:
    """A class for defining a flow network.

    A network object consists of a Node set and an Arc set.
    """

    pass
